<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>id7</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <Version>1.0.3</Version>
    <Authors>Yauhen Pyl</Authors>
    <Description>Tool to keep 7 ideas.</Description>
  </PropertyGroup>

</Project>
